### ISSUE TITLE
Broken by New API

### ISSUE THREAD

**Issue by rothn** [rothn/frigidaire_homeassistant#1]
There is a new OCP API out, and so the frigidaire API dependency needs to be changed to use it. Standby...

**Comment by sirjmann92** [comment]
The other Frigidaire integration is also broke. You seem to be first to acknowledge the issue.

Standing by for fix...

Thanks

**Comment by rothn** [comment]
Fixed and tested-working with Google Assistant and the dashboard.

**Comment by rothn** [comment]
@sirjmann92 Which other integration?

**Comment by sirjmann92** [comment]
@rothn - this one: https://github.com/bm1549/home-assistant-frigidaire

**Comment by sirjmann92** [comment]
Tested with a portable AC and it's working again with your updates. Thank you for getting on it so quickly. My dehumidifier isn't showing up anymore, but I think that's something on my end. I'll test more later.

**Comment by rothn** [comment]
@sirjmann92 The dehumidifier functionality is a known issue and being tracked in https://github.com/bm1549/home-assistant-frigidaire/issues/49#issuecomment-1918003436

**Comment by rothn** [comment]
I also worked with the package maintainer and the fix is now upstream and in the homeassistant integration. No need to use this repo anymore.

**Comment by sirjmann92** [comment]
Thanks, @rothn - I actually opened that issue :)

What do you mean there's no need to use this repo? Either one? Frigidaire integration is native to HA (or will be)?

**Comment by marty22877** [comment]
@rothn Does this still work for you?  I'm getting Unexpected error

**Comment by sirjmann92** [comment]
Not working again for me too... But it could be on Frigidaire's end. I can't log in with the app either. I opened a new issue, though, because I don't know if it's the same as this one reoccurring. https://github.com/bm1549/home-assistant-frigidaire/issues/54

**Comment by marty22877** [comment]
> Not working again for me too... But it could be on Frigidaire's end. I can't log in with the app either. I opened a new issue, though, because I don't know if it's the same as this one reoccurring. [bm1549/home-assistant-frigidaire#54](https://github.com/bm1549/home-assistant-frigidaire/issues/54)

I can log in on the app, but it asks me for a code, not my password.

**Comment by sirjmann92** [comment]
Must have been something on their end, it's working again after I was able to log in.

**Comment by marty22877** [comment]
> Must have been something on their end, it's working again after I was able to log in.

are you getting this now?  I think this was because of the upgrade:

![image](https://github.com/rothn/frigidaire_homeassistant/assets/30659144/6071e2d6-3b4b-4be3-8251-8879d9708dab)

**Comment by sirjmann92** [comment]
@marty22877,

I was getting a similar error from automations and the Service feature in the Dev menu of HA, yes.

If you don't have any other climate objects in your environment, and if you weren't able to log in to the Frigidaire integration, then your climate services would not exist, so calling the service or any automations that rely on it will obviously fail. I tested calling the climate service while I wasn't able to log in and that's when I received a similar error.

Things have been working fine for me for the last few days so I'm going to close the issue I opened related to this. I suggest you open a new issue if you're still having problems.

Good luck!

**Comment by marty22877** [comment]
> @marty22877,
> 
> I was getting a similar error from automations and the Service feature in the Dev menu of HA, yes.
> 
> If you don't have any other climate objects in your environment, and if you weren't able to log in to the Frigidaire integration, then your climate services would not exist, so calling the service or any automations that rely on it will obviously fail. I tested calling the climate service while I wasn't able to log in and that's when I received a similar error.
> 
> Things have been working fine for me for the last few days so I'm going to close the issue I opened related to this. I suggest you open a new issue if you're still having problems.
> 
> Good luck!

Oh I can log in and change the AC unit from Auto to Cool or Fan, it's just the fan speed I can't change.  I'll do some digging and if I still have an issue I'll submit a new one.  Thanks
